version: "3.6"
services:
  yamaha-http:
    container_name: yamaha-http
    build: .
    restart: unless-stopped
    environment:
      - YamahaReceiverUrl=http://10.0.0.14
    ports:
      - 7000:7000
